---
title: "Exploring ruby data"
author: "weixuan"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r tinytex, message=FALSE}
library(tinytex)
```



```{r tidivise, message=FALSE}
library(tidyverse)
```



## Read data

You can also embed plots, for example:

```{r read the rugby files}
df <- read_csv("2017_super-rugby_try-source-data.csv")
```

##str
```{r str rugby, warning=FALSE}
str(df)
```


## 

```{r row and colum}
which(rowSums(is.na(df)) == "0")

```

```{r load package ggplot2}
library(ggplot2)
```


```{r create graph attacking team}
ggplot(df, aes(x = attacking_team, fill =attacking_team, color = attacking_team)) +
  geom_bar() +
  xlab("attacking_team") +
  ylab("numbers of observations") +
  ggtitle("attcaking_team plot")

```

```{r garph with two variable }
ggplot(df, aes( x= total_passes, y = game_time)) +
  geom_point() +
  geom_smooth(method = "lm") +
  xlab("total_pass numbers") +
  ylab("game_time") +
  ggtitle("relationship between time and pass")
```
```{r dplyr}
library(dplyr)
```


```{r group_by}
df %>% 
  group_by(attacking_team) %>% 
  summarise(average_game_time = mean(game_time))
```

